=== ANR-ArTerm/index_oeuvres/schema/artwork.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://example.com/artwork.schema.json",
  "title": "Artwork Entry",
  "type": "object",
  "required": [
    "id",
    "entry_type",
    "title"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "QID_wikidata": {
      "type": "string"
    },
    "entry_type": {
      "type": "string",
      "enum": ["artwork"]
    },
    "title": {
      "type": "string"
    },
    "creator": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["xml_id", "role"],
        "properties": {
          "xml_id": {
            "type": "string"
          },
          "role": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "dateCreated": {
      "type": "object",
      "properties": {
        "startYear": {
          "type": ["integer", "null"],
          "minimum": -9999,
          "maximum": 9999
        },
        "endYear": {
          "type": ["integer", "null"],
          "minimum": -9999,
          "maximum": 9999
        },
        "text": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "materialsAndTechniques": {
      "type": "string"
    },
    "location": {
        "oneOf": [
            {
            "type": "object",
            "required": ["type", "institution"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["holding_institution"]
                },
                "institution": {
                "type": "object",
                "required": ["name"],
                "properties": {
                    "name": { "type": "string" },
                    "country": { "type": "string" },
                    "place": { "type": "string" },
                    "inventory_number": { "type": "string" },
                    "url": { "type": "string", "format": "uri" }
                },
                "additionalProperties": false
                }
            },
            "additionalProperties": false
            },
            {
            "type": "object",
            "required": ["type", "place"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["place"]
                },
                "place": {
                "type": "object",
                "properties": {
                    "city": { "type": "string" },
                    "country": { "type": "string" },
                    "coordinates": {
                    "type": "object",
                    "properties": {
                        "latitude": { "type": "number" },
                        "longitude": { "type": "number" }
                    },
                    "required": ["latitude", "longitude"],
                    "additionalProperties": false
                    }
                },
                "additionalProperties": false
                }
            },
            "additionalProperties": false
            },
            {
            "type": "object",
            "required": ["type"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["unlocated", "multiple_locations"]
                }
            },
            "additionalProperties": false
            }
        ]
    },
    "related_works": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["link_type", "xml_id_work"],
        "properties": {
          "link_type": {
            "type": "string"
          },
          "xml_id_work": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "contained_by_ensemble": {
      "type": "object",
      "properties": {
        "link_type": {
          "type": "string"
        },
        "xml_id_work": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "bibliography": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["zotero_key"],
        "properties": {
          "zotero_key": {
            "type": "string"
          },
          "location": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "illustrations": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["id", "url"],
        "properties": {
          "id": {
            "type": "integer"
          },
          "url": {
            "type": "string",
            "format": "uri"
          },
          "copyright": {
            "type": "string"
          },
          "caption": {
            "type": "string"
          },
          "storage": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "description": {
      "type": "string"
    },
    "commentary": {
      "type": "string"
    },
    "history": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["date", "type", "author"],
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "type": {
            "type": "string",
            "enum": ["created", "modified"]
          },
          "author": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "minItems": 1
    },
    "complete_entry": {
      "type":"boolean"
    }
  },
  "additionalProperties": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/RaphaelGracesFarnesina.json
{
  "id": "RaphaelGracesFarnesina",
  "QID_wikidata": "",
  "entry_type": "artwork",
  "title": "Cupidon et les grâces",
  "creator": [
    {
      "xml_id": "Raphael",
      "role": "peintre"
    },
    {
      "xml_id": "GiulioRomano",
      "role": "peintre"
    }
  ],
  "dateCreated": {
    "startYear": 1518,
    "endYear": 1518,
    "text": "1518"
  },
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "Villa Farnesina",
      "place": "Rome",
      "inventory_number": "",
      "url": ""
    }
  },
  "related_works": [
    {
      "link_type": "fait partie de",
      "xml_id_work": "LoggiaPsyche"
    }
  ],
  "bibliography": [],
  "illustrations": [
    {
      "id": 0,
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Raffael%2C_Loggia_di_Psiche%2C_Villa_Farnesina%2C_Rome_09.jpg",
      "storage": "online",
      "copyright": "Public Domain, Web Gallery of Art : https://www.wga.hu/index_artists.html, ",
      "caption": ""
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-01-27T17:19:04.614668",
      "type": "created",
      "author": "Carla"
    },
    {
      "date": "2026-02-04T16:10:24.415181",
      "type": "modified",
      "author": "Pierre"
    }
  ],
  "materialsAndTechniques": "fresque",
  "contained_by_ensemble": {},
  "complete_entry": false
}
